version: '2'
services:
  app:
    container_name: app
    environment:
      SERVICE_NAME: app
    ports:
    - "4000:4000"
    build: ./app

  stub:
    container_name: stub
    environment:
      SERVICE_NAME: stub
    ports:
    - "4001:4001"
    build: ./stub
